Add types for `cursor()` and `controller()` in mathquill.d.ts
Khan/mathquill pull request #19
Opened 2024-01-27 00:24 UTC by nishasy

## Summary:
todo

Issue: https://khanacademy.atlassian.net/browse/LC-1659

## Test plan:

todo

2024-01-27 01:33 UTC, nishasy commented on build/mathquill.d.ts
> +
**question**: I put these inside the `v3` namespace. Should they be outside, maybe around line 9 instead?

2024-01-27 01:34 UTC, nishasy commented on build/mathquill.d.ts
> +    interface NodeBase extends MQNode {
`extends MQNode` does not feel right to me here, but it's the only thing that worked with the rest of the types in Perseus.

2024-01-29 21:33 UTC, nedredmond requested changes
THanks Nisha! After merging my last PR, these would be overwritten on the next build, so we should explore some more options.

I'm okay with the cheap fix, which is adding these types to the namespace either in Build or in Perseus. However, I would like to try to pair on getting real exportable types.

Here's my text from the DM:

> Hey, whenever you're back we should think a bit more about the controller and cursor types, since the build step will now overwrite that file (or will when my PR to avoid manual fixing of build files is done).
I think it's valuable to be able to have one source of truth for code and types, so if you agree, I'd like to find a way to make our custom types work with that.
We have some choices:
- Add a dist-only declarations file that adds the types to the build.
  - This ranks 2nd for me. Makes things more complex.
- Inject our types via MakeFile.
  - Ranks last. Fragile, weird.
- Try again to incorporate it into the src declarations file.
  - I think this is the best choice, if we can manage it. I see two paths here:
    - This weekend I saw that we can declare class to create a class type. Maybe we can re-implement the whole thing after all?
    - I think the problem we were seeing last week was the partial type overriding the class. There must be a simple way to differentiate the results of cursor() from _controller.cursor(), and controller from _controller. Maybe if we gave them different names? CursorType, ICursor-- something like that.

2024-02-07 02:31 UTC, nishasy commented
Abandoning this because this approach would make it difficult to keep the build/ and src/ mathquill.d.ts files in sync.

2024-02-07 02:31 UTC, closed without merging